; ==============================================================================
; ORCUS Downloader - Inno Setup 6 Installer Script
; (C) Copyright 2026. OrcusExtreme
; Target: Windows 10/11 64-bit (Standalone, Self-contained)
; ==============================================================================

#define MyAppName "ORCUS Downloader"
#define MyAppVersion "1.0.4"
#define MyAppPublisher "OrcusExtreme"
#define MyAppURL "https://github.com/OrcusExtreme/ORCUS-Downloader"
#define MyAppExeName "ORCUS Downloader.exe"

[Setup]
; Unique application GUID for clean upgrade, overwrite, and uninstall tracking
AppId={{8B1D4F3C-2A5E-4B89-9F7C-90412E83FA21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}/issues
AppUpdatesURL={#MyAppURL}/releases

; Installation Directory (Default: C:\Program Files\ORCUS Downloader)
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes

; Required Administrator Privileges for writing to C:\Program Files
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible

; Installer appearance & branding
SetupIconFile=app_icon.ico
WizardStyle=modern
Compression=lzma2/ultra64
SolidCompression=yes

; Output settings
OutputDir=installer_output
OutputBaseFilename=ORCUS_Downloader_v{#MyAppVersion}_Setup

; Control Panel Add/Remove Programs (Uninstaller) Metadata
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
CloseApplications=yes
RestartIfNeededByRun=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
; Copy all files and directories generated by PyInstaller onedir mode
Source: "dist\ORCUS Downloader\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Source icon for shortcut referencing
Source: "app_icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Start Menu shortcuts
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

; Desktop shortcut (Optional checkbox in wizard)
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"; Tasks: desktopicon

[Run]
; Option to launch application immediately after setup completes
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
